In [40]:
#Python notebook by Piyush Bagani
#Some Basics of NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

In [3]:
#Once you've installed NumPy you can import it as a library:
import numpy as np

In [4]:
#Creating NumPy Arrays
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

Built-in Methods
--------------------------
arange

Return evenly spaced values within a given interval.


In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
#zeros and ones
#Generate arrays of zeros or ones
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
#linspace
#Return evenly spaced numbers over a specified interval.

np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
#eye
#Creates an identity matrix

np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
#Random
#Numpy also has lots of ways to create random number arrays:

#rand
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
np.random.rand(2)

array([0.96289832, 0.09160551])

In [15]:
np.random.rand(5,5)

array([[0.18476832, 0.67856059, 0.96990153, 0.46268644, 0.25536103],
       [0.44408294, 0.56499365, 0.33086656, 0.21806369, 0.94776987],
       [0.33466822, 0.6801994 , 0.21639172, 0.21170213, 0.06441335],
       [0.91635887, 0.97287625, 0.48353618, 0.60492307, 0.66617293],
       [0.27176646, 0.06510713, 0.73834802, 0.33174605, 0.65194778]])

In [16]:
#randn
#Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:
np.random.randn(2)

array([0.19759829, 0.09759114])

In [17]:
np.random.randn(5,5)

array([[ 1.32872431,  1.93224201, -0.5861009 , -0.810007  ,  0.45635604],
       [ 0.8829626 ,  0.28984297, -1.53298084, -1.05088842,  0.39626805],
       [-1.04674913, -0.50446337, -0.12680375, -0.11517849, -0.02298574],
       [ 1.52040922,  0.60569344,  0.04933458, -1.73309862,  0.68670675],
       [-0.86475646, -0.51166416, -0.13958906,  1.67625423,  1.02363352]])

In [18]:
#randint
#Return random integers from low (inclusive) to high (exclusive).

np.random.randint(1,100)

70

# Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [23]:
arr = np.arange(25)
arr_1 = np.linspace(0,25)
ranarr = np.random.randint(0,50,10)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr_1

array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
        2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
        5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
        7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
       10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
       12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
       15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
       17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
       20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
       22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ])

In [21]:
ranarr

array([13, 34,  8, 30, 26, 40,  9, 14, 10, 26])

In [25]:
#Reshape
#Returns an array containing the same data with a new shape.

arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
#Shape
#Shape is an attribute that arrays have (to be noted that it is not a method):
arr.shape #vector


(25,)

In [28]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [30]:
arr.dtype

dtype('int32')

In [31]:
#Broadcasting
#Numpy arrays differ from a normal Python list because of their ability to broadcast:

#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [32]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [33]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [34]:
#Indexing a 2D array (matrices)
#The general format is arr_2d[row][col] or arr_2d[row,col]


arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d[:1,1:]

array([[10, 15]])

In [39]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [41]:
#some Operations
arr.min()

6

In [42]:
arr.max()

99

In [43]:
arr.argmax()

0

In [44]:
arr.argmin()

6